### PR TITLE
Fixes issue #51

### LINKED ISSUE #51: Updating page questions deletes all answers
This should not happen because it loses application data

### PR DESCRIPTION
**Pull request by anttileppa**
Resolves #51

### CODE REVIEW

File: src/main/kotlin/fi/metatavu/oss/api/impl/pages/answers/repositories/PageAnswerSingleRepository.kt [hunk 1]
```diff
@@ -36,4 +37,14 @@ class PageAnswerSingleRepository : AbstractRepository<PageAnswerSingle, UUID>()
...
     }
+
+    /**
+     * Deletes suspending
+     *
+     * @param entity entity
+     */
+    override suspend fun deleteSuspending(entity: PageAnswerSingle) {
+        delete(entity).awaitSuspending()
+    }
```
Comment (villejuutila) [inline src/main/kotlin/fi/metatavu/oss/api/impl/pages/answers/repositories/PageAnswerSingleRepository.kt:48]: AbstractRepository already contains deleteSuspending method

**Review by villejuutila — APPROVED** [review]
